source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KLParallaxView_Example', :exclusive => true do
  pod "KLParallaxView", :path => "../"
end

target 'KLParallaxView_Tests', :exclusive => true do
  pod "KLParallaxView", :path => "../"

  
end
